In [1]:
import sys
from pathlib import Path

def find_project_root(markers=("src", "Data", "Notebooks")):
    current_path = Path.cwd().resolve()

    for path in [current_path] + list(current_path.parents):
        has_all_markers = all((path / marker).exists() for marker in markers)
        if has_all_markers:
            return path

    raise RuntimeError(
        f"Project root could not be found from: {current_path}"
    )

project_root = find_project_root()
src_path = project_root / "src"

if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import paths as P

In [2]:
import pandas as pd

merged_file = P.cleaned_dir / "merged_cleaned_data.xlsx"
merged_data = pd.read_excel(merged_file)

print("Merged data shape:")
print(merged_data.shape)
print()

print("First 10 columns:")
print(merged_data.columns.tolist()[:10])

Merged data shape:
(72, 56)

First 10 columns:
['please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'email', 'consent_to_proceed', 'pre_id', 'post_id', 'pre_start_time', 'post_start_time', 'pre_completion_time', 'post_completion_time', 'pre_name']

In [3]:
# define the 20 items under the five constructs

construct_items = {
    "cognitive_decision_making_confidence": [
        "i_can_identify_the_most_relevant_security_options_available_when_making_a_decision",
        "i_can_understand_the_potential_benefits_of_different_security_choices",
        "i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me",
        "i_can_interpret_technical_information_well_enough_to_make_an_informed_decision",
        "i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation"
    ],
    
    "behavioural_decision_making_confidence": [
        "i_can_make_security_related_decisions_without_feeling_uncertain",
        "i_can_express_concerns_about_different_security_options_effectively",
        "i_can_seek_advice_from_security_experts_or_colleagues_when_needed",
        "i_can_handle_pressure_when_making_security_decisions",
        "i_can_communicate_my_security_decisions_effectively_to_stakeholders"
    ],
    
    "cia_triad": [
        "i_can_define_the_confidentiality_component_of_the_cia_triad",
        "i_can_define_the_integrity_component_of_the_cia_triad",
        "i_can_define_the_availability_component_of_the_cia_triad"
    ],
    
    "access_control": [
        "i_can_explain_authentication_in_access_control",
        "i_can_explain_authorization_in_access_control"
    ],
    
    "malware_and_hacking": [
        "i_can_identify_different_types_of_malware_that_can_affect_information_security",
        "i_can_explain_how_malware_can_infiltrate_a_system",
        "i_can_describe_how_hacking_attacks_can_compromise_information_security",
        "i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system",
        "i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security"
    ]
}

for construct, items in construct_items.items():
    print(construct, ":", len(items), "items")

cognitive_decision_making_confidence : 5 items
behavioural_decision_making_confidence : 5 items
cia_triad : 3 items
access_control : 2 items
malware_and_hacking : 5 items

In [4]:
# check that all expected pre and post item columns exist in merged_data

missing_columns = []

for construct, items in construct_items.items():
    for item in items:
        pre_col = "pre_" + item
        post_col = "post_" + item
        
        if pre_col not in merged_data.columns:
            missing_columns.append(pre_col)
        if post_col not in merged_data.columns:
            missing_columns.append(post_col)

print("Missing columns:")
print(missing_columns)
print()

print("Number of missing columns:")
print(len(missing_columns))

Missing columns:
[]

Number of missing columns:
0

In [5]:
# item-level pre and post mean and standard deviation

item_results = []

for construct, items in construct_items.items():
    for item in items:
        pre_col = "pre_" + item
        post_col = "post_" + item
        
        pre_mean = merged_data[pre_col].mean()
        pre_sd = merged_data[pre_col].std()
        post_mean = merged_data[post_col].mean()
        post_sd = merged_data[post_col].std()
        
        item_results.append({
            "construct": construct,
            "item": item,
            "pre_mean": round(pre_mean, 3),
            "pre_sd": round(pre_sd, 3),
            "pre_mean_sd": f"{pre_mean:.2f} ({pre_sd:.2f})",
            "post_mean": round(post_mean, 3),
            "post_sd": round(post_sd, 3),
            "post_mean_sd": f"{post_mean:.2f} ({post_sd:.2f})"
        })

item_results = pd.DataFrame(item_results)

print("Item-level results:")
display(item_results)

Item-level results:

,construct,item,pre_mean,pre_sd,pre_mean_sd,post_mean,post_sd,post_mean_sd
0,cognitive_decision_making_confidence,i_can_identify_the_most_relevant_security_opti...,3.556,0.729,3.56 (0.73),4.056,0.603,4.06 (0.60)
1,cognitive_decision_making_confidence,i_can_understand_the_potential_benefits_of_dif...,4.069,0.635,4.07 (0.64),4.250,0.599,4.25 (0.60)
2,cognitive_decision_making_confidence,i_can_recognise_the_risks_or_vulnerabilities_a...,3.708,0.701,3.71 (0.70),4.194,0.642,4.19 (0.64)
3,cognitive_decision_making_confidence,i_can_interpret_technical_information_well_eno...,3.556,0.785,3.56 (0.79),4.000,0.732,4.00 (0.73)
4,cognitive_decision_making_confidence,i_can_determine_which_security_choice_best_fit...,3.333,0.872,3.33 (0.87),4.069,0.635,4.07 (0.64)
5,behavioural_decision_making_confidence,i_can_make_security_related_decisions_without_...,2.944,1.005,2.94 (1.01),3.750,0.884,3.75 (0.88)
6,behavioural_decision_making_confidence,i_can_express_concerns_about_different_securit...,3.569,0.819,3.57 (0.82),4.083,0.666,4.08 (0.67)
7,behavioural_decision_making_confidence,i_can_seek_advice_from_security_experts_or_col...,3.875,0.948,3.88 (0.95),4.069,0.793,4.07 (0.79)
8,behavioural_decision_making_confidence,i_can_handle_pressure_when_making_security_dec...,3.431,1.032,3.43 (1.03),3.792,0.918,3.79 (0.92)
9,behavioural_decision_making_confidence,i_can_communicate_my_security_decisions_effect...,3.236,1.000,3.24 (1.00),3.750,0.868,3.75 (0.87)
10,cia_triad,i_can_define_the_confidentiality_component_of_...,3.597,0.988,3.60 (0.99),3.833,1.061,3.83 (1.06)
11,cia_triad,i_can_define_the_integrity_component_of_the_ci...,3.583,0.975,3.58 (0.98),3.764,1.081,3.76 (1.08)
12,cia_triad,i_can_define_the_availability_component_of_the...,3.556,1.005,3.56 (1.01),3.778,1.038,3.78 (1.04)
13,access_control,i_can_explain_authentication_in_access_control,3.708,0.795,3.71 (0.80),4.014,0.796,4.01 (0.80)
14,access_control,i_can_explain_authorization_in_access_control,3.722,0.791,3.72 (0.79),3.986,0.796,3.99 (0.80)
15,malware_and_hacking,i_can_identify_different_types_of_malware_that...,3.528,0.888,3.53 (0.89),3.875,0.786,3.88 (0.79)
16,malware_and_hacking,i_can_explain_how_malware_can_infiltrate_a_system,3.597,0.781,3.60 (0.78),3.931,0.699,3.93 (0.70)
17,malware_and_hacking,i_can_describe_how_hacking_attacks_can_comprom...,3.778,0.736,3.78 (0.74),4.014,0.778,4.01 (0.78)
18,malware_and_hacking,i_can_identify_at_least_two_different_types_of...,3.569,0.901,3.57 (0.90),3.903,0.842,3.90 (0.84)
19,malware_and_hacking,i_can_apply_my_knowledge_of_attacks_to_make_in...,3.500,0.712,3.50 (0.71),4.069,0.793,4.07 (0.79)

In [6]:
# save item-level pre/post means and standard deviations
item_results.to_csv(P.tables_dir / "item_pre_post_means_sd.csv", index=False)

print("Saved item_pre_post_means_sd.csv")
print("Shape:", item_results.shape)

Saved item_pre_post_means_sd.csv
Shape: (20, 8)

In [7]:
# create construct-level pre and post mean scores for each student

for construct, items in construct_items.items():
    pre_cols = ["pre_" + item for item in items]
    post_cols = ["post_" + item for item in items]
    
    merged_data["pre_" + construct] = merged_data[pre_cols].mean(axis=1)
    merged_data["post_" + construct] = merged_data[post_cols].mean(axis=1)

construct_score_cols = [
    col for col in merged_data.columns
    if col.startswith("pre_") and col.replace("pre_", "", 1) in construct_items
] + [
    col for col in merged_data.columns
    if col.startswith("post_") and col.replace("post_", "", 1) in construct_items
]

print("Construct score columns created:")
print(construct_score_cols)

Construct score columns created:
['pre_cognitive_decision_making_confidence', 'pre_behavioural_decision_making_confidence', 'pre_cia_triad', 'pre_access_control', 'pre_malware_and_hacking', 'post_cognitive_decision_making_confidence', 'post_behavioural_decision_making_confidence', 'post_cia_triad', 'post_access_control', 'post_malware_and_hacking']

In [8]:
# construct-level pre and post mean and standard deviation

construct_results = []

for construct in construct_items.keys():
    pre_col = "pre_" + construct
    post_col = "post_" + construct
    
    pre_mean = merged_data[pre_col].mean()
    pre_sd = merged_data[pre_col].std()
    post_mean = merged_data[post_col].mean()
    post_sd = merged_data[post_col].std()
    
    construct_results.append({
        "construct": construct,
        "n_complete_pairs": merged_data[[pre_col, post_col]].dropna().shape[0],
        "pre_mean": round(pre_mean, 3),
        "pre_sd": round(pre_sd, 3),
        "pre_mean_sd": f"{pre_mean:.2f} ({pre_sd:.2f})",
        "post_mean": round(post_mean, 3),
        "post_sd": round(post_sd, 3),
        "post_mean_sd": f"{post_mean:.2f} ({post_sd:.2f})"
    })

construct_results = pd.DataFrame(construct_results)

display(construct_results)

,construct,n_complete_pairs,pre_mean,pre_sd,pre_mean_sd,post_mean,post_sd,post_mean_sd
0,cognitive_decision_making_confidence,72,3.644,0.575,3.64 (0.57),4.114,0.522,4.11 (0.52)
1,behavioural_decision_making_confidence,72,3.411,0.710,3.41 (0.71),3.889,0.631,3.89 (0.63)
2,cia_triad,72,3.579,0.964,3.58 (0.96),3.792,1.047,3.79 (1.05)
3,access_control,72,3.715,0.773,3.72 (0.77),4.000,0.783,4.00 (0.78)
4,malware_and_hacking,72,3.594,0.650,3.59 (0.65),3.958,0.652,3.96 (0.65)

In [9]:
# save construct-level pre/post means and standard deviations
construct_results.to_csv(P.tables_dir / "construct_pre_post_means_sd.csv", index=False)

print("Saved construct_pre_post_means_sd.csv")
print("Shape:", construct_results.shape)

Saved construct_pre_post_means_sd.csv
Shape: (5, 8)

In [10]:
# Cronbach alpha for each construct at pre and post

def cronbach_alpha(df):
    item_scores = df.dropna().copy()
    k = item_scores.shape[1]

    if k < 2:
        return pd.NA

    item_variances = item_scores.var(axis=0, ddof=1)
    total_score = item_scores.sum(axis=1)
    total_variance = total_score.var(ddof=1)

    if total_variance == 0:
        return pd.NA

    alpha = (k / (k - 1)) * (1 - (item_variances.sum() / total_variance))
    return alpha

construct_alpha_results = []

for construct, items in construct_items.items():
    pre_cols = ["pre_" + item for item in items]
    post_cols = ["post_" + item for item in items]

    alpha_pre = cronbach_alpha(merged_data[pre_cols])
    alpha_post = cronbach_alpha(merged_data[post_cols])

    construct_alpha_results.append({
        "construct": construct,
        "alpha_pre": round(alpha_pre, 3) if pd.notna(alpha_pre) else pd.NA,
        "alpha_post": round(alpha_post, 3) if pd.notna(alpha_post) else pd.NA
    })

construct_alpha_results = pd.DataFrame(construct_alpha_results)

print("Cronbach alpha results:")
display(construct_alpha_results)

Cronbach alpha results:

                                construct  alpha_pre  alpha_post
0    cognitive_decision_making_confidence      0.826       0.870
1  behavioural_decision_making_confidence      0.789       0.817
2                               cia_triad      0.973       0.988
3                          access_control      0.947       0.966
4                     malware_and_hacking      0.864       0.891

In [11]:
# save Cronbach alpha results
construct_alpha_results.to_csv(
    P.tables_dir / "construct_cronbach_alpha_summary.csv",
    index=False
)

print("Saved construct_cronbach_alpha_summary.csv")
print("Shape:", construct_alpha_results.shape)

Saved construct_cronbach_alpha_summary.csv
Shape: (5, 3)

In [12]:
# Shapiro-Wilk test on pre-post construct difference scores

from scipy.stats import shapiro

def format_p_value(p):
    if pd.isna(p):
        return pd.NA
    elif p < 0.001:
        return "<.001"
    else:
        return f"{p:.3f}"

construct_shapiro_results = []

for construct in construct_items.keys():
    pre_col = "pre_" + construct
    post_col = "post_" + construct

    diff_scores = (merged_data[post_col] - merged_data[pre_col]).dropna()

    shapiro_w, shapiro_p_value = shapiro(diff_scores)

    construct_shapiro_results.append({
        "construct": construct,
        "shapiro_w": round(shapiro_w, 3),
        "shapiro_p_value": shapiro_p_value,
        "shapiro_p": format_p_value(shapiro_p_value)
    })

construct_shapiro_results = pd.DataFrame(construct_shapiro_results)

print("Shapiro-Wilk results:")
display(construct_shapiro_results[["construct", "shapiro_w", "shapiro_p"]])

Shapiro-Wilk results:

                                construct  shapiro_w shapiro_p
0    cognitive_decision_making_confidence      0.965     0.045
1  behavioural_decision_making_confidence      0.972     0.107
2                               cia_triad      0.759     <.001
3                          access_control      0.787     <.001
4                     malware_and_hacking      0.929     <.001

In [13]:
# save Shapiro-Wilk results
construct_shapiro_results.to_csv(
    P.tables_dir / "construct_shapiro_normality_summary.csv",
    index=False
)

print("Saved construct_shapiro_normality_summary.csv")
print("Shape:", construct_shapiro_results.shape)

Saved construct_shapiro_normality_summary.csv
Shape: (5, 4)

In [14]:
# combine construct results with alpha and Shapiro results

construct_results_reliability_normality = (
    construct_results
    .merge(construct_alpha_results, on="construct", how="left")
    .merge(construct_shapiro_results, on="construct", how="left")
)

print("Construct results with reliability and normality:")
display(
    construct_results_reliability_normality[
        [
            "construct",
            "n_complete_pairs",
            "pre_mean",
            "pre_sd",
            "pre_mean_sd",
            "post_mean",
            "post_sd",
            "post_mean_sd",
            "alpha_pre",
            "alpha_post",
            "shapiro_w",
            "shapiro_p"
        ]
    ]
)

Construct results with reliability and normality:

,construct,n_complete_pairs,pre_mean,pre_sd,pre_mean_sd,post_mean,post_sd,post_mean_sd,alpha_pre,alpha_post,shapiro_w,shapiro_p
0,cognitive_decision_making_confidence,72,3.644,0.575,3.64 (0.57),4.114,0.522,4.11 (0.52),0.826,0.870,0.965,0.045
1,behavioural_decision_making_confidence,72,3.411,0.710,3.41 (0.71),3.889,0.631,3.89 (0.63),0.789,0.817,0.972,0.107
2,cia_triad,72,3.579,0.964,3.58 (0.96),3.792,1.047,3.79 (1.05),0.973,0.988,0.759,<.001
3,access_control,72,3.715,0.773,3.72 (0.77),4.000,0.783,4.00 (0.78),0.947,0.966,0.787,<.001
4,malware_and_hacking,72,3.594,0.650,3.59 (0.65),3.958,0.652,3.96 (0.65),0.864,0.891,0.929,<.001

In [15]:
# save combined reliability and normality summary
construct_results_reliability_normality.to_csv(
    P.tables_dir / "construct_reliability_and_normality_summary.csv",
    index=False
)

print("Saved construct_reliability_and_normality_summary.csv")
print("Shape:", construct_results_reliability_normality.shape)

Saved construct_reliability_and_normality_summary.csv
Shape: (5, 13)

In [17]:
# decide which test to use for each construct
# keep numeric p-values for logic, but show formatted p-values in the table

construct_test_plan = construct_shapiro_results[["construct", "shapiro_p_value", "shapiro_p"]].copy()

construct_test_plan["recommended_test"] = construct_test_plan["shapiro_p_value"].apply(
    lambda p: "paired_t_test" if p > 0.05 else "wilcoxon_signed_rank"
)

print("Recommended test for each construct:")
display(
    construct_test_plan[
        ["construct", "shapiro_p", "recommended_test"]
    ]
)

Recommended test for each construct:

                                construct shapiro_p      recommended_test
0    cognitive_decision_making_confidence     0.045  wilcoxon_signed_rank
1  behavioural_decision_making_confidence     0.107         paired_t_test
2                               cia_triad     <.001  wilcoxon_signed_rank
3                          access_control     <.001  wilcoxon_signed_rank
4                     malware_and_hacking     <.001  wilcoxon_signed_rank

In [19]:
# run paired t-test or Wilcoxon signed-rank based on the Shapiro result

from scipy.stats import ttest_rel, wilcoxon

def format_p_value(p):
    if pd.isna(p):
        return pd.NA
    elif p < 0.001:
        return "<.001"
    else:
        return f"{p:.3f}"

construct_test_results = []

for _, row in construct_test_plan.iterrows():
    construct = row["construct"]
    recommended_test = row["recommended_test"]

    pre_col = "pre_" + construct
    post_col = "post_" + construct

    paired_data = merged_data[[pre_col, post_col]].dropna().copy()
    pre_scores = paired_data[pre_col]
    post_scores = paired_data[post_col]

    if recommended_test == "paired_t_test":
        test_statistic, p_value = ttest_rel(post_scores, pre_scores)
        test_used = "Paired t-test"
        df = len(paired_data) - 1
    else:
        test_statistic, p_value = wilcoxon(post_scores, pre_scores)
        test_used = "Wilcoxon signed-rank"
        df = pd.NA

    construct_test_results.append({
        "construct": construct,
        "test_used": test_used,
        "test_statistic": round(test_statistic, 3),
        "df": df,
        "p_value": format_p_value(p_value)
    })

construct_test_results = pd.DataFrame(construct_test_results)

print("Construct-level test results:")
display(construct_test_results)

Construct-level test results:

,construct,test_used,test_statistic,df,p_value
0,cognitive_decision_making_confidence,Wilcoxon signed-rank,113.500,<NA>,<.001
1,behavioural_decision_making_confidence,Paired t-test,7.954,71,<.001
2,cia_triad,Wilcoxon signed-rank,48.500,<NA>,0.001
3,access_control,Wilcoxon signed-rank,32.500,<NA>,<.001
4,malware_and_hacking,Wilcoxon signed-rank,147.000,<NA>,<.001

In [20]:
# save construct-level test results
construct_test_results.to_csv(
    P.tables_dir / "construct_ttest_wilcoxon_summary.csv",
    index=False
)

print("Saved construct_ttest_wilcoxon_summary.csv")
print("Shape:", construct_test_results.shape)

Saved construct_ttest_wilcoxon_summary.csv
Shape: (5, 5)

In [21]:
# combine means, reliability, normality, and test results

construct_results_with_tests = (
    construct_results_reliability_normality
    .merge(construct_test_results, on="construct", how="left")
)

print("Construct results with tests:")
display(
    construct_results_with_tests[
        [
            "construct",
            "n_complete_pairs",
            "pre_mean",
            "pre_sd",
            "pre_mean_sd",
            "post_mean",
            "post_sd",
            "post_mean_sd",
            "alpha_pre",
            "alpha_post",
            "shapiro_w",
            "shapiro_p",
            "test_used",
            "test_statistic",
            "df",
            "p_value"
        ]
    ]
)

Construct results with tests:

,construct,n_complete_pairs,pre_mean,pre_sd,pre_mean_sd,post_mean,post_sd,post_mean_sd,alpha_pre,alpha_post,shapiro_w,shapiro_p,test_used,test_statistic,df,p_value
0,cognitive_decision_making_confidence,72,3.644,0.575,3.64 (0.57),4.114,0.522,4.11 (0.52),0.826,0.870,0.965,0.045,Wilcoxon signed-rank,113.500,<NA>,<.001
1,behavioural_decision_making_confidence,72,3.411,0.710,3.41 (0.71),3.889,0.631,3.89 (0.63),0.789,0.817,0.972,0.107,Paired t-test,7.954,71,<.001
2,cia_triad,72,3.579,0.964,3.58 (0.96),3.792,1.047,3.79 (1.05),0.973,0.988,0.759,<.001,Wilcoxon signed-rank,48.500,<NA>,0.001
3,access_control,72,3.715,0.773,3.72 (0.77),4.000,0.783,4.00 (0.78),0.947,0.966,0.787,<.001,Wilcoxon signed-rank,32.500,<NA>,<.001
4,malware_and_hacking,72,3.594,0.650,3.59 (0.65),3.958,0.652,3.96 (0.65),0.864,0.891,0.929,<.001,Wilcoxon signed-rank,147.000,<NA>,<.001

In [22]:
# save combined construct results with tests
construct_results_with_tests.to_csv(
    P.tables_dir / "construct_reliability_normality_test_summary.csv",
    index=False
)

print("Saved construct_reliability_normality_test_summary.csv")
print("Shape:", construct_results_with_tests.shape)

Saved construct_reliability_normality_test_summary.csv
Shape: (5, 17)

In [ ]:
# paired Cohen's d and 95% bootstrap confidence intervals

import numpy as np

def paired_cohens_d(pre_scores, post_scores):
    diff_scores = post_scores - pre_scores
    diff_sd = diff_scores.std(ddof=1)

    if diff_sd == 0:
        return pd.NA

    return diff_scores.mean() / diff_sd

def interpret_cohens_d(d):
    if pd.isna(d):
        return pd.NA
    elif d < 0.2:
        return "negligible"
    elif d < 0.5:
        return "small"
    elif d < 0.8:
        return "medium"
    else:
        return "large"

construct_effect_size_results = []

rng = np.random.default_rng(42)
n_boot = 5000

for construct in construct_items.keys():
    pre_col = "pre_" + construct
    post_col = "post_" + construct

    paired_data = merged_data[[pre_col, post_col]].dropna().copy()
    pre_scores = paired_data[pre_col].to_numpy()
    post_scores = paired_data[post_col].to_numpy()

    d_value = paired_cohens_d(pre_scores, post_scores)

    boot_d_values = []

    for _ in range(n_boot):
        sample_idx = rng.choice(len(paired_data), size=len(paired_data), replace=True)
        boot_pre = pre_scores[sample_idx]
        boot_post = post_scores[sample_idx]
        boot_d = paired_cohens_d(boot_pre, boot_post)

        if pd.notna(boot_d):
            boot_d_values.append(boot_d)

    d_ci_low, d_ci_high = np.percentile(boot_d_values, [2.5, 97.5])

    construct_effect_size_results.append({
        "construct": construct,
        "cohens_d": round(d_value, 3) if pd.notna(d_value) else pd.NA,
        "d_ci_low": round(d_ci_low, 3),
        "d_ci_high": round(d_ci_high, 3),
        "effect_size_interpretation": interpret_cohens_d(d_value)
    })

construct_effect_size_results = pd.DataFrame(construct_effect_size_results)

print("Construct effect size results:")
display(construct_effect_size_results)

Construct effect size results:

,construct,cohens_d,d_ci_low,d_ci_high,effect_size_interpretation
0,cognitive_decision_making_confidence,1.042,0.754,1.444,large
1,behavioural_decision_making_confidence,0.937,0.684,1.274,large
2,cia_triad,0.433,0.205,0.670,small
3,access_control,0.525,0.329,0.728,medium
4,malware_and_hacking,0.747,0.536,1.003,medium

In [25]:
# save effect size results

construct_effect_size_results.to_csv(
    P.tables_dir / "construct_paired_cohens_d_ci_summary.csv",
    index=False
)

print("Saved construct_paired_cohens_d_ci_summary.csv")
print("Shape:", construct_effect_size_results.shape)

Saved construct_paired_cohens_d_ci_summary.csv
Shape: (5, 5)

In [ ]:
# combine test results with effect sizes

construct_results_final = (
    construct_results_with_tests
    .merge(construct_effect_size_results, on="construct", how="left")
)

print("Final construct results:")
display(
    construct_results_final[
        [
            "construct",
            "n_complete_pairs",
            "pre_mean",
            "pre_sd",
            "pre_mean_sd",
            "post_mean",
            "post_sd",
            "post_mean_sd",
            "alpha_pre",
            "alpha_post",
            "shapiro_w",
            "shapiro_p",
            "test_used",
            "test_statistic",
            "df",
            "p_value",
            "cohens_d",
            "d_ci_low",
            "d_ci_high",
            "effect_size_interpretation"
        ]
    ]
)

Final construct results:

,construct,n_complete_pairs,pre_mean,pre_sd,pre_mean_sd,post_mean,post_sd,post_mean_sd,alpha_pre,alpha_post,shapiro_w,shapiro_p,test_used,test_statistic,df,p_value,cohens_d,d_ci_low,d_ci_high,effect_size_interpretation
0,cognitive_decision_making_confidence,72,3.644,0.575,3.64 (0.57),4.114,0.522,4.11 (0.52),0.826,0.870,0.965,0.045,Wilcoxon signed-rank,113.500,<NA>,<.001,1.042,0.754,1.444,large
1,behavioural_decision_making_confidence,72,3.411,0.710,3.41 (0.71),3.889,0.631,3.89 (0.63),0.789,0.817,0.972,0.107,Paired t-test,7.954,71,<.001,0.937,0.684,1.274,large
2,cia_triad,72,3.579,0.964,3.58 (0.96),3.792,1.047,3.79 (1.05),0.973,0.988,0.759,<.001,Wilcoxon signed-rank,48.500,<NA>,0.001,0.433,0.205,0.670,small
3,access_control,72,3.715,0.773,3.72 (0.77),4.000,0.783,4.00 (0.78),0.947,0.966,0.787,<.001,Wilcoxon signed-rank,32.500,<NA>,<.001,0.525,0.329,0.728,medium
4,malware_and_hacking,72,3.594,0.650,3.59 (0.65),3.958,0.652,3.96 (0.65),0.864,0.891,0.929,<.001,Wilcoxon signed-rank,147.000,<NA>,<.001,0.747,0.536,1.003,medium

In [26]:
# save final construct summary with tests and effect sizes

construct_results_final.to_csv(
    P.tables_dir / "construct_final_results_summary.csv",
    index=False
)

print("Saved construct_final_results_summary.csv")
print("Shape:", construct_results_final.shape)

Saved construct_final_results_summary.csv
Shape: (5, 21)