In [1]:
import sys
from pathlib import Path

def find_project_root(markers=("src", "Data", "Notebooks")):
    current_path = Path.cwd().resolve()

    for path in [current_path] + list(current_path.parents):
        has_all_markers = all((path / marker).exists() for marker in markers)
        if has_all_markers:
            return path

    raise RuntimeError(
        f"Project root could not be found from: {current_path}"
    )

project_root = find_project_root()
src_path = project_root / "src"

if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import paths as P

In [2]:
import pandas as pd

pre_numeric_file = P.survey_data_numeric_dir / "[Pre-Survey] CyberSecSim_ Integrating Cyber Incident Scenarios into CyberSecurity Curricula(1-88).xlsx"
post_numeric_file = P.survey_data_numeric_dir / "[PostSurvey] CyberSecSim_ Integrating Cyber Incident Scenarios into CyberSecurity Curricula(1-78).xlsx"

pre_data = pd.read_excel(pre_numeric_file)
post_data = pd.read_excel(post_numeric_file)

print("Pre-survey shape:")
print(pre_data.shape)
print()

print("Post-survey shape:")
print(post_data.shape)
print()

print("Pre-survey columns:")
print(pre_data.columns.tolist())
print()

print("Post-survey columns:")
print(post_data.columns.tolist())

Pre-survey shape:
(88, 29)

Post-survey shape:
(78, 30)

Pre-survey columns:
['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Consent to proceed', 'Please provide your student number (please note this is only used to\xa0enable matching of the pre- and post-intervention survey data enable\xa0matching of the pre- and post-intervention survey data):\xa0', 'Please\xa0indicate\xa0your level of study\xa0', 'I can\xa0identify\xa0the most relevant security options available when\xa0making a decision.', 'I can understand the potential benefits of different security choices.\xa0', 'I can recognise the risks or vulnerabilities associated with security options available to me.', 'I can interpret technical information well enough to make an informed decision.\xa0', 'I can\xa0determine\xa0which security choice best fits the needs of my environment or organisation.', 'I can make security related decisions without feeling uncertain.\xa0', 'I can express concerns about different security options effectively.', 'I can seek advice from security experts or colleagues when needed.', 'I can handle pressure when making security decisions.\xa0', 'I can communicate my security decisions effectively to stakeholders.', 'I can define the confidentiality\xa0component\xa0of the CIA triad.', 'I can define the integrity\xa0component\xa0of the CIA triad.', 'I can define the availability\xa0component\xa0of the CIA triad.', 'I can explain authentication in access control.', 'I can explain authorization in access control.', 'I can\xa0identify\xa0different types\xa0of\xa0malware\xa0that can affect information security.', 'I can explain how malware can infiltrate a system.', 'I can describe how hacking attacks can compromise information security', 'I can\xa0identify\xa0at least two\xa0different types\xa0of vulnerabilities in a system.', 'I can apply my knowledge of attacks to make informed decisions about information security.']

Post-survey columns:
['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Consent to proceed', 'Please provide your student number (please note this is only used to\xa0enable matching of the pre- and post-intervention survey data enable\xa0matching of the pre- and post-intervention survey data):\xa0', 'Please\xa0indicate\xa0your level of study\xa0', 'I can\xa0identify\xa0the most relevant security options available when\xa0making a decision.', 'I can understand the potential benefits of different security choices.\xa0', 'I can recognise the risks or vulnerabilities associated with security options available to me.', 'I can interpret technical information well enough to make an informed decision.\xa0', 'I can\xa0determine\xa0which security choice best fits the needs of my environment or organisation.', 'I can make security related decisions without feeling uncertain.\xa0', 'I can express concerns about different security options effectively.', 'I can seek advice from security experts or colleagues when needed.', 'I can handle pressure when making security decisions.\xa0', 'I can communicate my security decisions effectively to stakeholders.', 'I can define the confidentiality\xa0component\xa0of the CIA triad.', 'I can define the integrity\xa0component\xa0of the CIA triad.', 'I can define the availability\xa0component\xa0of the CIA triad.', 'I can explain authentication in access control.', 'I can explain authorization in access control.', 'I can\xa0identify\xa0different types\xa0of\xa0malware\xa0that can affect information security.', 'I can explain how malware can infiltrate a system.', 'I can describe how hacking attacks can compromise information security', 'I can\xa0identify\xa0at least two\xa0different types\xa0of vulnerabilities in a system.', 'I can apply my knowledge of attacks to make informed decisions about information security.', 'I would be happy to be contacted about participating in a follow-up focus-group to talk about the CyberSecSim simulation and provide comments on what was good/bad etc']

In [3]:
# check missing values and duplicate rows in the original datasets

print("Pre-survey missing values:")
print(pre_data.isna().sum())
print()

Pre-survey missing values:
ID                                                                                                                                                                                                      0
Start time                                                                                                                                                                                              0
Completion time                                                                                                                                                                                         0
Email                                                                                                                                                                                                   0
Name                                                                                                                                                                                                   88
Last modified time                                                                                                                                                                                     88
Consent to proceed                                                                                                                                                                                      0
Please provide your student number (please note this is only used to enable matching of the pre- and post-intervention survey data enable matching of the pre- and post-intervention survey data):      0
Please indicate your level of study                                                                                                                                                                     0
I can identify the most relevant security options available when making a decision.                                                                                                                     0
I can understand the potential benefits of different security choices.                                                                                                                                  0
I can recognise the risks or vulnerabilities associated with security options available to me.                                                                                                          0
I can interpret technical information well enough to make an informed decision.                                                                                                                         0
I can determine which security choice best fits the needs of my environment or organisation.                                                                                                            0
I can make security related decisions without feeling uncertain.                                                                                                                                        0
I can express concerns about different security options effectively.                                                                                                                                    0
I can seek advice from security experts or colleagues when needed.                                                                                                                                      0
I can handle pressure when making security decisions.                                                                                                                                                   0
I can communicate my security decisions effectively to stakeholders.                                                                                                                                    0
I can define the confidentiality component of the CIA triad.                                                                                                                                            0
I can define the integrity component of the CIA triad.                                                                                                                                                  0
I can define the availability component of the CIA triad.                                                                                                                                               0
I can explain authentication in access control.                                                                                                                                                         0
I can explain authorization in access control.                                                                                                                                                          0
I can identify different types of malware that can affect information security.                                                                                                                         0
I can explain how malware can infiltrate a system.                                                                                                                                                      0
I can describe how hacking attacks can compromise information security                                                                                                                                  0
I can identify at least two different types of vulnerabilities in a system.                                                                                                                             0
I can apply my knowledge of attacks to make informed decisions about information security.                                                                                                              0
dtype: int64

In [4]:
print("Pre-survey duplicate rows:")
print(pre_data.duplicated().sum())
print()

Pre-survey duplicate rows:
0

In [5]:
print("Post-survey missing values:")
print(post_data.isna().sum())
print()

Post-survey missing values:
ID                                                                                                                                                                                                      0
Start time                                                                                                                                                                                              0
Completion time                                                                                                                                                                                         0
Email                                                                                                                                                                                                   0
Name                                                                                                                                                                                                   78
Last modified time                                                                                                                                                                                     78
Consent to proceed                                                                                                                                                                                      0
Please provide your student number (please note this is only used to enable matching of the pre- and post-intervention survey data enable matching of the pre- and post-intervention survey data):      0
Please indicate your level of study                                                                                                                                                                     0
I can identify the most relevant security options available when making a decision.                                                                                                                     0
I can understand the potential benefits of different security choices.                                                                                                                                  0
I can recognise the risks or vulnerabilities associated with security options available to me.                                                                                                          0
I can interpret technical information well enough to make an informed decision.                                                                                                                         0
I can determine which security choice best fits the needs of my environment or organisation.                                                                                                            0
I can make security related decisions without feeling uncertain.                                                                                                                                        0
I can express concerns about different security options effectively.                                                                                                                                    0
I can seek advice from security experts or colleagues when needed.                                                                                                                                      0
I can handle pressure when making security decisions.                                                                                                                                                   0
I can communicate my security decisions effectively to stakeholders.                                                                                                                                    0
I can define the confidentiality component of the CIA triad.                                                                                                                                            0
I can define the integrity component of the CIA triad.                                                                                                                                                  0
I can define the availability component of the CIA triad.                                                                                                                                               0
I can explain authentication in access control.                                                                                                                                                         0
I can explain authorization in access control.                                                                                                                                                          0
I can identify different types of malware that can affect information security.                                                                                                                         0
I can explain how malware can infiltrate a system.                                                                                                                                                      0
I can describe how hacking attacks can compromise information security                                                                                                                                  0
I can identify at least two different types of vulnerabilities in a system.                                                                                                                             0
I can apply my knowledge of attacks to make informed decisions about information security.                                                                                                              0
I would be happy to be contacted about participating in a follow-up focus-group to talk about the CyberSecSim simulation and provide comments on what was good/bad etc                                  0
dtype: int64

In [6]:
print("Post-survey duplicate rows:")
print(post_data.duplicated().sum())

Post-survey duplicate rows:
0

In [7]:
# create working copies after the initial checks
pre_clean = pre_data.copy()
post_clean = post_data.copy()

print("Pre working copy shape:", pre_clean.shape)
print("Post working copy shape:", post_clean.shape)

Pre working copy shape: (88, 29)
Post working copy shape: (78, 30)

In [8]:
# standardise column names in pre_clean
pre_clean.columns = (
    pre_clean.columns
    .str.replace("\xa0", " ", regex=False)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace(r"[^\w]", "", regex=True)
)

print("Pre-survey cleaned column names:")
print(pre_clean.columns.tolist())

Pre-survey cleaned column names:
['id', 'start_time', 'completion_time', 'email', 'name', 'last_modified_time', 'consent_to_proceed', 'please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'please_indicate_your_level_of_study', 'i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'i_can_understand_the_potential_benefits_of_different_security_choices', 'i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me', 'i_can_interpret_technical_information_well_enough_to_make_an_informed_decision', 'i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation', 'i_can_make_security_related_decisions_without_feeling_uncertain', 'i_can_express_concerns_about_different_security_options_effectively', 'i_can_seek_advice_from_security_experts_or_colleagues_when_needed', 'i_can_handle_pressure_when_making_security_decisions', 'i_can_communicate_my_security_decisions_effectively_to_stakeholders', 'i_can_define_the_confidentiality_component_of_the_cia_triad', 'i_can_define_the_integrity_component_of_the_cia_triad', 'i_can_define_the_availability_component_of_the_cia_triad', 'i_can_explain_authentication_in_access_control', 'i_can_explain_authorization_in_access_control', 'i_can_identify_different_types_of_malware_that_can_affect_information_security', 'i_can_explain_how_malware_can_infiltrate_a_system', 'i_can_describe_how_hacking_attacks_can_compromise_information_security', 'i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system', 'i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security']

In [9]:
# standardise column names in post_clean
post_clean.columns = (
    post_clean.columns
    .str.replace("\xa0", " ", regex=False)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace(r"[^\w]", "", regex=True)
)

print("Post-survey cleaned column names:")
print(post_clean.columns.tolist())

Post-survey cleaned column names:
['id', 'start_time', 'completion_time', 'email', 'name', 'last_modified_time', 'consent_to_proceed', 'please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'please_indicate_your_level_of_study', 'i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'i_can_understand_the_potential_benefits_of_different_security_choices', 'i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me', 'i_can_interpret_technical_information_well_enough_to_make_an_informed_decision', 'i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation', 'i_can_make_security_related_decisions_without_feeling_uncertain', 'i_can_express_concerns_about_different_security_options_effectively', 'i_can_seek_advice_from_security_experts_or_colleagues_when_needed', 'i_can_handle_pressure_when_making_security_decisions', 'i_can_communicate_my_security_decisions_effectively_to_stakeholders', 'i_can_define_the_confidentiality_component_of_the_cia_triad', 'i_can_define_the_integrity_component_of_the_cia_triad', 'i_can_define_the_availability_component_of_the_cia_triad', 'i_can_explain_authentication_in_access_control', 'i_can_explain_authorization_in_access_control', 'i_can_identify_different_types_of_malware_that_can_affect_information_security', 'i_can_explain_how_malware_can_infiltrate_a_system', 'i_can_describe_how_hacking_attacks_can_compromise_information_security', 'i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system', 'i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security', 'i_would_be_happy_to_be_contacted_about_participating_in_a_followup_focusgroup_to_talk_about_the_cybersecsim_simulation_and_provide_comments_on_what_was_goodbad_etc']

In [10]:
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

print("Pre-survey student number examples:")
print(pre_clean[student_col].head(15))
print()

print("Post-survey student number examples:")
print(post_clean[student_col].head(15))
print()

print("Pre-survey unique count:", pre_clean[student_col].nunique())
print("Post-survey unique count:", post_clean[student_col].nunique())

Pre-survey student number examples:
0     S4513221
1     s4508532
2     s4510408
3      4220908
4     s4501945
5     s4503819
6     S4510329
7      4512742
8     S4510009
9     S4511946
10    S4509779
11    s4509934
12    s4408192
13     4517034
14          22
Name: please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data, dtype: object

Post-survey student number examples:
0                 4511622
1                s4510945
2                 4517034
3                s4510408
4                S4513221
5                s4503819
6                s4510329
7                S4510009
8                 4220908
9     s4508532@glos.ac.uk
10               s4408192
11               S4512829
12               s4509934
13               s4511946
14               S4509936
Name: please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data, dtype: object

Pre-survey unique count: 88
Post-survey unique count: 78

In [11]:
# inspect pre-survey student number entries that do not contain any digits
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_no_digits = pre_clean[
    ~pre_clean[student_col].astype(str).str.contains(r"\d", regex=True, na=False)
].copy()

print("Pre-survey entries with no digits in the student number field:")
print(pre_no_digits[[student_col]])
print()
print("Count:", pre_no_digits.shape[0])

Pre-survey entries with no digits in the student number field:
   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
37                                      Barry Hopkins
70                                        Billy Floyd

Count: 2

In [12]:
# inspect post-survey student number entries that do not contain any digits
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

post_no_digits = post_clean[
    ~post_clean[student_col].astype(str).str.contains(r"\d", regex=True, na=False)
].copy()

print("Post-survey entries with no digits in the student number field:")
print(post_no_digits[[student_col]])
print()
print("Count:", post_no_digits.shape[0])

Post-survey entries with no digits in the student number field:
   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
64                                       john johnson

Count: 1

In [13]:
# check whether any no-digit name entries match between pre and post
pre_name_entries = (
    pre_no_digits[student_col]
    .astype(str)
    .str.strip()
    .str.lower()
)

post_name_entries = (
    post_no_digits[student_col]
    .astype(str)
    .str.strip()
    .str.lower()
)

name_matches = set(pre_name_entries).intersection(set(post_name_entries))

print("Name-only matches between pre and post:")
print(name_matches)
print()
print("Number of matches:", len(name_matches))

Name-only matches between pre and post:
set()

Number of matches: 0

In [ ]:
# check Jordan's provided IDs against post-survey and update pre_clean before cleaning
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

name_id_map = {
    "Barry Hopkins": "4524369",
    "Billy Floyd": "4403075"
}

post_check_ids = (
    post_clean[student_col]
    .astype(str)
    .str.strip()
    .str.replace(r"\D", "", regex=True)
)

for name, student_id in name_id_map.items():
    name_in_pre = pre_clean[student_col].astype(str).str.strip().eq(name).any()
    id_in_post = post_check_ids.eq(student_id).any()
    
    print(f"{name} -> {student_id}")
    print("Found name in pre-survey:", name_in_pre)
    print("Found ID in post-survey:", id_in_post)
    
    if name_in_pre and id_in_post:
        pre_clean.loc[
            pre_clean[student_col].astype(str).str.strip() == name,
            student_col
        ] = student_id
        print("Updated pre-survey entry with the student ID.")
    else:
        print("Not updated.")
    
    print()

print("Updated pre-survey values for these cases:")
print(
    pre_clean.loc[
        pre_clean[student_col].astype(str).isin(name_id_map.values()),
        ["id", student_col]
    ]
)

Barry Hopkins -> 4524369
Found name in pre-survey: True
Found ID in post-survey: True
Updated pre-survey entry with the student ID.

Billy Floyd -> 4403075
Found name in pre-survey: True
Found ID in post-survey: False
Not updated.

Updated pre-survey values for these cases:
    id  \
37  39

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
37                                            4524369

In [15]:
# re-check pre-survey entries with no digits after updating known IDs
pre_no_digits = pre_clean[
    ~pre_clean[student_col].astype(str).str.contains(r"\d", regex=True, na=False)
].copy()

print("Pre-survey entries with no digits in the student number field after update:")
print(pre_no_digits[["id", student_col]])
print()
print("Count:", pre_no_digits.shape[0])

Pre-survey entries with no digits in the student number field after update:
    id  \
70  72

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
70                                        Billy Floyd

Count: 1

In [16]:
# clean the student number column in pre_clean
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_clean[student_col] = (
    pre_clean[student_col]
    .astype(str)
    .str.strip()
    .str.replace(r"\D", "", regex=True)
    .replace("", pd.NA)
)

print("Pre-survey cleaned student number examples:")
print(pre_clean[student_col].head(15))
print()

print("Missing values in pre-survey student number column after cleaning:")
print(pre_clean[student_col].isna().sum())

Pre-survey cleaned student number examples:
0     4513221
1     4508532
2     4510408
3     4220908
4     4501945
5     4503819
6     4510329
7     4512742
8     4510009
9     4511946
10    4509779
11    4509934
12    4408192
13    4517034
14         22
Name: please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data, dtype: object

Missing values in pre-survey student number column after cleaning:
1

In [17]:
# remove the remaining pre-survey row with no usable student number after the update
# and no possible name-only match in post-survey

pre_missing_ids = pre_clean.loc[
    pre_clean[student_col].isna(),
    "id"
].tolist()

pre_clean = pre_clean[~pre_clean["id"].isin(pre_missing_ids)].copy()

print("Removed pre-survey ids:", pre_missing_ids)
print()

print("Pre-survey shape after removing that row:")
print(pre_clean.shape)
print()

print("Check removed ids still exist:")
print(pre_clean["id"].isin(pre_missing_ids).sum())

Removed pre-survey ids: [72]

Pre-survey shape after removing that row:
(87, 29)

Check removed ids still exist:
0

In [18]:
# check duplicate student numbers inside pre_clean after cleaning
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_duplicate_student_numbers = pre_clean[
    pre_clean[student_col].duplicated(keep=False) & pre_clean[student_col].notna()
].copy()

print("Duplicate cleaned student numbers in pre-survey:")
print(pre_duplicate_student_numbers[["id", "completion_time", student_col]].sort_values(by=student_col))
print()

print("Count of rows involved in duplicates:")
print(pre_duplicate_student_numbers.shape[0])

Duplicate cleaned student numbers in pre-survey:
    id     completion_time  \
22  24 2026-04-13 14:28:20
40  42 2026-04-13 14:30:47

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
22                                            4515151
40                                            4515151

Count of rows involved in duplicates:
2

In [19]:
# compare the two pre-survey rows for the duplicated student number
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_duplicate_compare = pre_clean[
    pre_clean[student_col] == "4515151"
].copy()

print("Rows found:")
print(pre_duplicate_compare.shape[0])
print()

display(pre_duplicate_compare.T)

Rows found:
2

,22,40
id,24,42
start_time,2026-04-13 14:26:00,2026-04-13 14:29:55
completion_time,2026-04-13 14:28:20,2026-04-13 14:30:47
email,anonymous,anonymous
name,NaN,NaN
last_modified_time,NaN,NaN
consent_to_proceed,I agree and wish to continue to the survey.,I agree and wish to continue to the survey.
please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data,4515151,4515151
please_indicate_your_level_of_study,Level 3,Level 4
i_can_identify_the_most_relevant_security_options_available_when_making_a_decision,3,3
i_can_understand_the_potential_benefits_of_different_security_choices,4,4
i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me,4,4
i_can_interpret_technical_information_well_enough_to_make_an_informed_decision,4,4
i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation,4,4
i_can_make_security_related_decisions_without_feeling_uncertain,4,4
i_can_express_concerns_about_different_security_options_effectively,3,4
i_can_seek_advice_from_security_experts_or_colleagues_when_needed,4,4
i_can_handle_pressure_when_making_security_decisions,4,4
i_can_communicate_my_security_decisions_effectively_to_stakeholders,4,4
i_can_define_the_confidentiality_component_of_the_cia_triad,3,3
i_can_define_the_integrity_component_of_the_cia_triad,3,3
i_can_define_the_availability_component_of_the_cia_triad,3,3
i_can_explain_authentication_in_access_control,4,4
i_can_explain_authorization_in_access_control,4,4
i_can_identify_different_types_of_malware_that_can_affect_information_security,4,4
i_can_explain_how_malware_can_infiltrate_a_system,4,4
i_can_describe_how_hacking_attacks_can_compromise_information_security,4,4
i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system,4,4
i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security,4,4

In [20]:
# show only the columns that differ between the two duplicate pre-survey rows
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_duplicate_compare = pre_clean[
    pre_clean[student_col] == "4515151"
].copy()

different_cols = pre_duplicate_compare.nunique(dropna=False) > 1
different_values = pre_duplicate_compare.loc[:, different_cols]

display(different_values.T)

,22,40
id,24,42
start_time,2026-04-13 14:26:00,2026-04-13 14:29:55
completion_time,2026-04-13 14:28:20,2026-04-13 14:30:47
please_indicate_your_level_of_study,Level 3,Level 4
i_can_express_concerns_about_different_security_options_effectively,3,4

In [21]:
# remove the earlier pre-survey duplicate and keep the latest submission
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

pre_clean["completion_time"] = pd.to_datetime(pre_clean["completion_time"])

pre_clean = (
    pre_clean
    .sort_values("completion_time")
    .drop_duplicates(subset=student_col, keep="last")
    .copy()
)

print("Pre-survey shape after removing the earlier duplicate:")
print(pre_clean.shape)
print()

print("Remaining duplicate student numbers in pre-survey:")
print(pre_clean[student_col].duplicated().sum())

Pre-survey shape after removing the earlier duplicate:
(86, 29)

Remaining duplicate student numbers in pre-survey:
0

In [22]:
# final check for missing student numbers in pre_clean
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

print("Missing student numbers in cleaned pre-survey:")
print(pre_clean[student_col].isna().sum())
print()

print("Pre-survey shape:")
print(pre_clean.shape)

Missing student numbers in cleaned pre-survey:
0

Pre-survey shape:
(86, 29)

In [23]:
#correct level of study for these two pre-survey students
level_col = "please_indicate_your_level_of_study"

pre_clean.loc[
 pre_clean[student_col].isin(["4510329", "4408192"]),
   level_col
] = "Level 4"

print(
   pre_clean.loc[
       pre_clean[student_col].isin(["4510329", "4408192"]),
      ["id", student_col, level_col]
    ]
)

    id  \
6    8
12  14

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data  \
6                                             4510329
12                                            4408192

   please_indicate_your_level_of_study
6                              Level 4
12                             Level 4

In [24]:
# save cleaned pre-survey dataset
pre_clean.to_csv(P.cleaned_dir / "pre_cleaned.csv", index=False)

print("Saved pre_cleaned.csv")
print("Shape:", pre_clean.shape)

Saved pre_cleaned.csv
Shape: (86, 29)

In [25]:
# clean the student number column in post_clean
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

post_clean[student_col] = (
    post_clean[student_col]
    .astype(str)
    .str.strip()
    .str.replace(r"\D", "", regex=True)
)

post_clean[student_col] = post_clean[student_col].replace("", pd.NA)

print("Post-survey cleaned student number examples:")
print(post_clean[student_col].head(15))
print()

print("Missing values in post-survey student number column after cleaning:")
print(post_clean[student_col].isna().sum())

Post-survey cleaned student number examples:
0     4511622
1     4510945
2     4517034
3     4510408
4     4513221
5     4503819
6     4510329
7     4510009
8     4220908
9     4508532
10    4408192
11    4512829
12    4509934
13    4511946
14    4509936
Name: please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data, dtype: object

Missing values in post-survey student number column after cleaning:
1

In [26]:
# inspect the post-survey row where student number became missing after cleaning
student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

post_missing_student = post_clean[post_clean[student_col].isna()].copy()

print("Post-survey rows with missing student number after cleaning:")
print(post_missing_student[["id", "start_time", "completion_time", student_col]])
print()

print("Count:")
print(post_missing_student.shape[0])

Post-survey rows with missing student number after cleaning:
    id          start_time     completion_time  \
64  65 2026-04-14 14:56:11 2026-04-14 14:57:55

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data
64                                               <NA>

Count:
1

In [27]:
# remove the post-survey row with no usable student number
post_clean = post_clean[post_clean[student_col].notna()].copy()

print("Post-survey shape after removing missing student number row:")
print(post_clean.shape)
print()

print("Missing student numbers in cleaned post-survey:")
print(post_clean[student_col].isna().sum())

Post-survey shape after removing missing student number row:
(77, 30)

Missing student numbers in cleaned post-survey:
0

In [28]:
# check duplicate student numbers in post_clean
post_duplicate_student_numbers = post_clean[
    post_clean[student_col].duplicated(keep=False)
].copy()

print("Duplicate cleaned student numbers in post-survey:")
print(post_duplicate_student_numbers[["id", "completion_time", student_col]].sort_values(by=student_col))
print()

print("Count of rows involved in duplicates:")
print(post_duplicate_student_numbers.shape[0])

Duplicate cleaned student numbers in post-survey:
Empty DataFrame
Columns: [id, completion_time, please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data]
Index: []

Count of rows involved in duplicates:
0

In [29]:
# correct level of study for these two post-survey students before saving
level_col = "please_indicate_your_level_of_study"

post_clean.loc[
   post_clean[student_col].isin(["4510329", "4408192"]),
   level_col
] = "Level 4"

print(
    post_clean.loc[
        post_clean[student_col].isin(["4510329", "4408192"]),
        ["id", student_col, level_col]
    ]
)

    id  \
6    7
10  11

   please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data  \
6                                             4510329
10                                            4408192

   please_indicate_your_level_of_study
6                              Level 4
10                             Level 4

In [30]:
# save cleaned post-survey dataset
post_clean.to_csv(P.cleaned_dir / "post_cleaned.csv", index=False)

print("Saved post_cleaned.csv")
print("Shape:", post_clean.shape)

Saved post_cleaned.csv
Shape: (77, 30)

In [31]:
# create prefixed versions for merging
# keep student number, email, and consent_to_proceed only once
# drop email and consent_to_proceed from post_clean before merging

student_col = "please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data"

keep_once_cols = [student_col, "email", "consent_to_proceed"]

pre_merge = pre_clean.rename(
    columns={col: f"pre_{col}" for col in pre_clean.columns if col not in keep_once_cols}
).copy()

post_merge = post_clean.drop(columns=["email", "consent_to_proceed"]).copy()

post_merge = post_merge.rename(
    columns={col: f"post_{col}" for col in post_merge.columns if col != student_col}
)

print("Pre merge columns:")
print(pre_merge.columns.tolist())
print()

print("Post merge columns:")
print(post_merge.columns.tolist())

Pre merge columns:
['pre_id', 'pre_start_time', 'pre_completion_time', 'email', 'pre_name', 'pre_last_modified_time', 'consent_to_proceed', 'please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'pre_please_indicate_your_level_of_study', 'pre_i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'pre_i_can_understand_the_potential_benefits_of_different_security_choices', 'pre_i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me', 'pre_i_can_interpret_technical_information_well_enough_to_make_an_informed_decision', 'pre_i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation', 'pre_i_can_make_security_related_decisions_without_feeling_uncertain', 'pre_i_can_express_concerns_about_different_security_options_effectively', 'pre_i_can_seek_advice_from_security_experts_or_colleagues_when_needed', 'pre_i_can_handle_pressure_when_making_security_decisions', 'pre_i_can_communicate_my_security_decisions_effectively_to_stakeholders', 'pre_i_can_define_the_confidentiality_component_of_the_cia_triad', 'pre_i_can_define_the_integrity_component_of_the_cia_triad', 'pre_i_can_define_the_availability_component_of_the_cia_triad', 'pre_i_can_explain_authentication_in_access_control', 'pre_i_can_explain_authorization_in_access_control', 'pre_i_can_identify_different_types_of_malware_that_can_affect_information_security', 'pre_i_can_explain_how_malware_can_infiltrate_a_system', 'pre_i_can_describe_how_hacking_attacks_can_compromise_information_security', 'pre_i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system', 'pre_i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security']

Post merge columns:
['post_id', 'post_start_time', 'post_completion_time', 'post_name', 'post_last_modified_time', 'please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'post_please_indicate_your_level_of_study', 'post_i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'post_i_can_understand_the_potential_benefits_of_different_security_choices', 'post_i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me', 'post_i_can_interpret_technical_information_well_enough_to_make_an_informed_decision', 'post_i_can_determine_which_security_choice_best_fits_the_needs_of_my_environment_or_organisation', 'post_i_can_make_security_related_decisions_without_feeling_uncertain', 'post_i_can_express_concerns_about_different_security_options_effectively', 'post_i_can_seek_advice_from_security_experts_or_colleagues_when_needed', 'post_i_can_handle_pressure_when_making_security_decisions', 'post_i_can_communicate_my_security_decisions_effectively_to_stakeholders', 'post_i_can_define_the_confidentiality_component_of_the_cia_triad', 'post_i_can_define_the_integrity_component_of_the_cia_triad', 'post_i_can_define_the_availability_component_of_the_cia_triad', 'post_i_can_explain_authentication_in_access_control', 'post_i_can_explain_authorization_in_access_control', 'post_i_can_identify_different_types_of_malware_that_can_affect_information_security', 'post_i_can_explain_how_malware_can_infiltrate_a_system', 'post_i_can_describe_how_hacking_attacks_can_compromise_information_security', 'post_i_can_identify_at_least_two_different_types_of_vulnerabilities_in_a_system', 'post_i_can_apply_my_knowledge_of_attacks_to_make_informed_decisions_about_information_security', 'post_i_would_be_happy_to_be_contacted_about_participating_in_a_followup_focusgroup_to_talk_about_the_cybersecsim_simulation_and_provide_comments_on_what_was_goodbad_etc']

In [32]:
# merge using exact matching student numbers only
# keep student number, email, and consent_to_proceed once
# place pre and post versions side by side

merged_data = pd.merge(
    pre_merge,
    post_merge,
    on=student_col,
    how="inner"
).copy()

ordered_cols = [student_col, "email", "consent_to_proceed"]

pre_cols = [
    col for col in pre_merge.columns
    if col not in [student_col, "email", "consent_to_proceed"]
]

post_cols = [
    col for col in post_merge.columns
    if col != student_col
]

pre_base_names = [col.replace("pre_", "", 1) for col in pre_cols]
post_base_names = [col.replace("post_", "", 1) for col in post_cols]

for base_name in pre_base_names:
    pre_col = "pre_" + base_name
    post_col = "post_" + base_name

    if pre_col in merged_data.columns:
        ordered_cols.append(pre_col)
    if post_col in merged_data.columns:
        ordered_cols.append(post_col)

for base_name in post_base_names:
    post_col = "post_" + base_name
    if post_col not in ordered_cols:
        ordered_cols.append(post_col)

merged_data = merged_data[ordered_cols]

print("Merged dataset shape:")
print(merged_data.shape)
print()

print("First 20 merged columns:")
print(merged_data.columns.tolist()[:20])

Merged dataset shape:
(72, 56)

First 20 merged columns:
['please_provide_your_student_number_please_note_this_is_only_used_to_enable_matching_of_the_pre_and_postintervention_survey_data_enable_matching_of_the_pre_and_postintervention_survey_data', 'email', 'consent_to_proceed', 'pre_id', 'post_id', 'pre_start_time', 'post_start_time', 'pre_completion_time', 'post_completion_time', 'pre_name', 'post_name', 'pre_last_modified_time', 'post_last_modified_time', 'pre_please_indicate_your_level_of_study', 'post_please_indicate_your_level_of_study', 'pre_i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'post_i_can_identify_the_most_relevant_security_options_available_when_making_a_decision', 'pre_i_can_understand_the_potential_benefits_of_different_security_choices', 'post_i_can_understand_the_potential_benefits_of_different_security_choices', 'pre_i_can_recognise_the_risks_or_vulnerabilities_associated_with_security_options_available_to_me']

In [33]:
# check matched and unmatched student numbers after merge
match_check = pd.merge(
    pre_clean[[student_col]],
    post_clean[[student_col]],
    on=student_col,
    how="outer",
    indicator=True
)

print("Match summary:")
print(match_check["_merge"].value_counts())

Match summary:
_merge
both          72
left_only     14
right_only     5
Name: count, dtype: int64

In [34]:
# save the cleaned merged dataset
merged_data.to_csv(P.cleaned_dir / "merged_cleaned_data.csv", index=False)

print("Saved merged_cleaned_data.csv")
print("Shape:", merged_data.shape)

Saved merged_cleaned_data.csv
Shape: (72, 56)

In [35]:
# save the cleaned merged dataset as Excel
merged_data.to_excel(P.cleaned_dir / "merged_cleaned_data.xlsx", index=False)

print("Saved merged_cleaned_data.xlsx")

Saved merged_cleaned_data.xlsx